# Generated by Django 5.2.7 on 2025-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preim',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
