# Generated by Django 5.2.7 on 2025-11-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_preim_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(max_length=255, verbose_name='Должность')),
                ('img', models.ImageField(blank=True, null=True, upload_to='employee/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='preim',
            options={'ordering': ['order'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
    ]
