# Generated by Django 5.2.7 on 2025-11-10 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='reviews/sources/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Источник отзыва',
                'verbose_name_plural': 'Источники отзыва',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('date', models.DateField(verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Текст')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reviewsource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['date'],
            },
        ),
    ]
