# Generated by Django 5.2.2 on 2025-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='img',
            field=models.ImageField(default='', upload_to='methods/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
