# Generated by Django 5.2.2 on 2025-11-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_method_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='methods/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ['order'],
            },
        ),
    ]
