# Generated by Django 5.2.2 on 2025-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_etap'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_desc', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO desc')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Заголовок (первый экран)')),
                ('hero_desc', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание (первый экран)')),
                ('hero_bg_img', models.ImageField(blank=True, null=True, upload_to='services/hero/', verbose_name='Фоновая картинка (первый экран')),
                ('about_company_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (о компании)')),
                ('about_company_text', models.TextField(blank=True, max_length=255, null=True, verbose_name='Текст (о компании)')),
                ('about_company_img', models.ImageField(upload_to='about_company/', verbose_name='Изображение (о компании)')),
                ('about_company_numbers', models.ManyToManyField(blank=True, related_name='homapage_about_company_numbers', to='main.number', verbose_name='Цифры (о компании)')),
                ('hero_numbers', models.ManyToManyField(blank=True, related_name='homapage_hero_numbers', to='main.number', verbose_name='Цифры (первый экран)')),
                ('preims', models.ManyToManyField(blank=True, to='main.preim', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
