# Generated by Django 5.2.2 on 2025-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_company_img',
            field=models.ImageField(blank=True, null=True, upload_to='about_company/', verbose_name='Изображение (о компании)'),
        ),
    ]
