# Generated by Django 5.2.2 on 2025-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_homepage_about_company_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEtap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='history_etaps/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Этап истории',
                'verbose_name_plural': 'Этапы истории',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='history_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (история компании)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='history_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (история компании)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='history_etaps',
            field=models.ManyToManyField(blank=True, to='main.historyetap', verbose_name='Этапы истории'),
        ),
    ]
