# Generated by Django 5.2.2 on 2025-12-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_historyetap_homepage_history_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (услуги)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='history_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (услуги)'),
        ),
    ]
