# Generated by Django 5.2.2 on 2025-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_homepage_services_title_alter_homepage_history_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='history_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (история компании)'),
        ),
    ]
