# Generated by Django 5.2.2 on 2025-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_homepage_history_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (услуги)'),
        ),
    ]
