# Generated by Django 5.2.2 on 2025-12-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_homepage_services_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='faqs',
            field=models.ManyToManyField(blank=True, to='main.faq', verbose_name='FAQS'),
        ),
    ]
