# Generated by Django 5.2.2 on 2026-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_homepage_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_company_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст (о компании)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (первый экран)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_desc',
            field=models.TextField(blank=True, null=True, verbose_name='SEO desc'),
        ),
    ]
