# Generated by Django 5.2.2 on 2026-01-23 10:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_homepage_about_company_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('block', models.CharField(choices=[('#preims', 'Преимущества'), ('#quiz', 'Квиз'), ('#about-activities', 'О компании'), ('#sertificatesslider', 'Сертификаты (слайдер)'), ('#promotions', 'Акции'), ('#typesgrid', 'Дочерние услуги'), ('#price', 'Прайс'), ('#calc', 'Калькулятор'), ('#calc2', 'Калькулятор 2'), ('#methods', 'Способы'), ('#machines', 'Техника'), ('#etaps', 'Этапы'), ('#etaps2', 'Этапы 2'), ('#commandslider', 'Команда'), ('#partnersslider', 'Партнеры'), ('#worksmap', 'Работы'), ('#reviewsslider', 'Отзывы'), ('#faq', 'Вопрос-ответ')], max_length=255, verbose_name='Блок')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Якорь',
                'verbose_name_plural': 'Якоря',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='technic',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
