# Generated by Django 5.2.2 on 2026-02-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_homepage_anchors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='block',
            field=models.CharField(choices=[('#preims', 'Преимущества'), ('#quiz', 'Квиз'), ('#about-activities', 'О нашей деятельности'), ('#about_company', 'О компании'), ('#sertificatesslider', 'Сертификаты (слайдер)'), ('#promotions', 'Акции'), ('#typesgrid', 'Дочерние услуги'), ('#price', 'Прайс'), ('#calc', 'Калькулятор'), ('#calc2', 'Калькулятор 2'), ('#methods', 'Способы'), ('#machines', 'Техника'), ('#etaps', 'Этапы'), ('#etaps2', 'Этапы 2'), ('#commandslider', 'Команда'), ('#partnersslider', 'Партнеры'), ('#worksmap', 'Работы'), ('#reviewsslider', 'Отзывы'), ('#faq', 'Вопрос-ответ')], max_length=255, verbose_name='Блок'),
        ),
    ]
