# Generated by Django 5.2.7 on 2025-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_desc',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание (первый экран)'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (первый экран)'),
        ),
    ]
