# Generated by Django 5.2.7 on 2025-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_hero_desc_service_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/', verbose_name='Фоновая картинка (первый экран'),
        ),
    ]
