# Generated by Django 5.2.7 on 2025-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_number'),
        ('services', '0004_service_hero_bg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_numbers',
            field=models.ManyToManyField(blank=True, to='main.number', verbose_name='Цифры (первый экран)'),
        ),
    ]
