# Generated by Django 5.2.7 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_number'),
        ('services', '0005_service_hero_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preims',
            field=models.ManyToManyField(blank=True, to='main.preim', verbose_name='Преимущества'),
        ),
    ]
