# Generated by Django 5.2.2 on 2025-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sertificate'),
        ('services', '0006_service_preims'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sertificates',
            field=models.ManyToManyField(blank=True, to='main.sertificate', verbose_name='Сертификаты'),
        ),
    ]
