# Generated by Django 5.2.2 on 2025-11-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quiz'),
        ('services', '0007_service_sertificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.quiz', verbose_name='Квиз'),
        ),
    ]
