# Generated by Django 5.2.2 on 2025-11-27 06:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='textblock_img',
            field=models.ImageField(blank=True, null=True, upload_to='services/textblock/', verbose_name='Изображение (текстовый блок)'),
        ),
        migrations.AddField(
            model_name='service',
            name='textblock_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст (текстовый блок)'),
        ),
    ]
