# Generated by Django 5.2.2 on 2025-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_promotion'),
        ('services', '0009_service_textblock_img_service_textblock_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='main.promotion', verbose_name='Акции'),
        ),
    ]
