# Generated by Django 5.2.2 on 2025-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='childrens_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок дочерних услуг'),
        ),
    ]
