# Generated by Django 5.2.2 on 2025-11-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_service_childrens_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
    ]
