# Generated by Django 5.2.2 on 2025-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='properties',
            field=models.ManyToManyField(blank=True, to='services.property', verbose_name='Характеристики'),
        ),
    ]
