# Generated by Django 5.2.2 on 2025-11-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_priceposition'),
        ('services', '0013_property_service_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_positions',
            field=models.ManyToManyField(blank=True, to='main.priceposition', verbose_name='Позиции прайса'),
        ),
    ]
