# Generated by Django 5.2.2 on 2025-11-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_service_price_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_calc',
            field=models.BooleanField(default=False, verbose_name='Показывать калькулятор расчета стоимости бурения и обустройства скважины'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_calc_2',
            field=models.BooleanField(default=False, verbose_name='Показывать калькулятор расчета стоимости канализационной насосной станции'),
        ),
    ]
