# Generated by Django 5.2.2 on 2025-11-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_method'),
        ('services', '0015_service_show_calc_service_show_calc_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='methods',
            field=models.ManyToManyField(blank=True, to='main.method', verbose_name='Способы бурения'),
        ),
        migrations.AddField(
            model_name='service',
            name='methods_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (способы бурения)'),
        ),
        migrations.AddField(
            model_name='service',
            name='methods_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок (способы бурения)'),
        ),
        migrations.AddField(
            model_name='service',
            name='methods_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (способы бурения)'),
        ),
    ]
