# Generated by Django 5.2.2 on 2025-11-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_methods_service_methods_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='methods_bg',
            field=models.ImageField(blank=True, null=True, upload_to='methods/bg/', verbose_name='Фоновое изображение (способы бурения)'),
        ),
    ]
