# Generated by Django 5.2.2 on 2025-11-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_technic'),
        ('services', '0017_service_methods_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='technics',
            field=models.ManyToManyField(blank=True, to='main.technic', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='service',
            name='technics_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (техника)'),
        ),
    ]
