# Generated by Django 5.2.2 on 2025-11-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_etap'),
        ('services', '0018_service_technics_service_technics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='etaps',
            field=models.ManyToManyField(blank=True, to='main.etap', verbose_name='Этапы'),
        ),
        migrations.AddField(
            model_name='service',
            name='etaps_img',
            field=models.ImageField(blank=True, null=True, upload_to='etaps/', verbose_name='Изображение (этапы)'),
        ),
        migrations.AddField(
            model_name='service',
            name='etaps_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок (этапы)'),
        ),
        migrations.AddField(
            model_name='service',
            name='etaps_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (этапы)'),
        ),
    ]
