# Generated by Django 5.2.2 on 2025-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_etap'),
        ('services', '0019_service_etaps_service_etaps_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='main.review', verbose_name='Отзывы'),
        ),
    ]
