# Generated by Django 5.2.2 on 2025-11-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_etap'),
        ('services', '0020_service_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.ManyToManyField(blank=True, to='main.faq', verbose_name='FAQS'),
        ),
    ]
