# Generated by Django 5.2.2 on 2026-01-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_homepage_about_company_text_and_more'),
        ('services', '0022_alter_service_hero_desc_alter_service_seo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='etaps2',
            field=models.ManyToManyField(blank=True, related_name='etaps2_service', to='main.etap', verbose_name='Этапы 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='etaps2_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок (этапы 2)'),
        ),
        migrations.AddField(
            model_name='service',
            name='etaps2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (этапы 2)'),
        ),
    ]
