# Generated by Django 5.2.2 on 2026-01-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_service_etaps2_service_etaps2_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='etaps2_subtitle',
        ),
    ]
