# Generated by Django 5.2.2 on 2026-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_remove_service_etaps2_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='consult_title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок заказа консультации'),
        ),
    ]
