# Generated by Django 5.2.2 on 2026-01-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_service_consult_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc_listing',
            field=models.TextField(blank=True, null=True, verbose_name='Описание в списке'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_listing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в списке'),
        ),
    ]
