# Generated by Django 5.2.2 on 2026-01-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_anchor_alter_technic_desc'),
        ('services', '0026_service_desc_listing_service_name_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='anchors',
            field=models.ManyToManyField(blank=True, to='main.anchor', verbose_name='Якоря'),
        ),
    ]
