# Generated by Django 5.2.2 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('working_house', models.CharField(max_length=255, verbose_name='Рабочие часы')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('map_mapker', models.CharField(max_length=255, verbose_name='Метка на карте')),
                ('img', models.ImageField(blank=True, null=True, upload_to='contacts/offices/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
                'ordering': ['order'],
            },
        ),
    ]
