# Generated by Django 5.2.2 on 2026-01-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('adress_link', models.URLField(verbose_name='Ссылка проложить маршрут')),
                ('phone_1', models.CharField(max_length=255, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(max_length=255, verbose_name='Телефон 2')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
