# Generated by Django 5.2.2 on 2026-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='conpany_name',
            field=models.TextField(default='-', verbose_name='Название огранизации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='inn_kpp',
            field=models.CharField(default='-', max_length=255, verbose_name='ИНН/КПП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='ogrn',
            field=models.CharField(default='-', max_length=255, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='vk',
            field=models.CharField(default='-', max_length=255, verbose_name='Вконтакте'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(default='-', max_length=255, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
    ]
