# Generated by Django 5.2.2 on 2026-02-11 07:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contacts_conpany_name_contacts_inn_kpp_contacts_ogrn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='cookie_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст cookie'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='policy_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст политики конфиденциальности'),
        ),
    ]
