# Generated by Django 5.2.2 on 2026-02-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contacts_cookie_text_contacts_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='cookie_text_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок cookie'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='policy_text_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок политики конфиденциальности'),
        ),
    ]
