# Generated by Django 5.2.2 on 2025-11-29 12:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0015_etap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_desc', models.TextField(blank=True, max_length=255, null=True, verbose_name='SEO desc')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='SLUG')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('img', models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='Изображение')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('numbers', models.ManyToManyField(blank=True, to='main.number', verbose_name='Цифры')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
