# Generated by Django 5.2.2 on 2025-11-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='text',
        ),
    ]
