# Generated by Django 5.2.2 on 2025-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_work_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
