# Generated by Django 5.2.2 on 2025-12-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_service_faqs'),
        ('works', '0003_work_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Услуга'),
        ),
    ]
