# Generated by Django 5.2.2 on 2025-12-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='map_marker',
            field=models.CharField(blank=True, help_text='Пример: 55.829173, 49.043343', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
    ]
